/*
** EPITECH PROJECT, 2021
** CPP_rtype_2018
** File description:
** Created by kellian CIPIERRE,
*/

#ifndef CPP_RTYPE_2018_COMMANDTYPE_HPP
#define CPP_RTYPE_2018_COMMANDTYPE_HPP

enum CommandType {
    UNDEFINED_CMD = -1,
    JOIN_INSTANCE = 0,
    JOIN_INSTANCE_RESPONSE,
    VALID_USER,
    CREATE_INSTANCE,
    CREATE_INSTANCE_RESPONSE,
    LIST_INSTANCES,
    LIST_INSTANCES_RESPONSE,
    SLOT_STATUS,
    SLOT_STATUS_RESPONSE,
    JOIN_SLOT,
    JOIN_SLOT_RESPONSE,
    LEAVE_SLOT,
    LEAVE_SLOT_RESPONSE,
    PLAYER_READY,
    PLAYER_READY_RESPONSE,
    ALL_PLAYER_READY,
    LEAVE_INSTANCE,
    PLAYER_ALIVE,
    INPUT_KEY,
    UPDATE_ENTITY,
    GAME_PLAYER_STATUS,
    GAME_PLAYER_ALIVE,
    GAME_MOVE_UP,
    GAME_MOVE_DOWN,
    GAME_MOVE_LEFT,
    GAME_MOVE_RIGHT,
    GAME_ATTACK,
    CREATE_LIBRARY,
    END_GAME,
	DISCONNECT_CLIENT,
	DISCONNECT_SERVER
};


#endif //CPP_RTYPE_2018_COMMANDTYPE_HPP
